[theme]
background = "black"
primary = "light white"
secondary = "light black"
title = "blue"
playing = "black"
playing_selected = "black"
playing_bg = "green"
highlight = "black"
highlight_bg = "blue"
error = "black"
error_bg = "red"
statusbar = "blue"
statusbar_progress = "green"
statusbar_bg = "black"
cmdline = "light white"
cmdline_bg = "black"
